apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - certs.yaml
  - release.yaml
  - jaeger.yaml
  - dashboard.yaml
patches:
  - target:
      version: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: prometheus-kube-prometheus-kubelet
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec
        value:
          endpoints:
          - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            interval: 10s
            port: https-metrics
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
          - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
            honorLabels: true
            interval: 10s
            path: /metrics/cadvisor
            port: https-metrics
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
  - target:
      version: monitoring.coreos.com/v1
      kind: Prometheus
      name: prometheus-kube-prometheus-prometheus
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/additionalScrapeConfigs/name                 
        value: prometheus-kube-prometheus-prometheus-scrape-confg-linkerd 