
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd 
  namespace: linkerd 
spec:
  releaseName: linkerd 
  chart:
    spec:
      chart: linkerd2 
      version: '2.10.0'
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: linkerd-trust-anchor
      valuesKey: tls.crt
      targetPath: global.identityTrustAnchorsPEM     
  values:
    installNamespace: false
    prometheus:
      enabled: false
    identity:
      issuer:
        scheme: kubernetes.io/tls   
