apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqVENDQVRPZ0F3SUJBZ0lRSFl6dGY0RmdueGMvd1RjS3psSlhtVEFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU1URXdNVFl3TVRVMQpOREphRncwek1URXdNVFF3TVRVMU5ESmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVpqUGtoaVY5RDJWc1FNSncKbU1jaGE0QmYvSjRBakE5c3lUZFVBKzNVdFJudThpM2RuM3NxSFZqWmRNNXdTQ0tDMUdVMml2cHArcnBVNkljZgpKYkM0VnFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRkhZSjJKVlFEYlc3YXk4MjFCSFRsR2UxYnpvck1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQ2MKKzVBb2w0SDlUcWVlQnlzbmJKVkZVWEpuZlNiTmZ3UjdWSmYyRkFLQTVBSWdaTU1MdkpyUkhJRWZHUURIeWJ0aApPd3JoNXlsSmhKTC9adXM4UXJnVzQ3RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSVBjYlp1ZThNeFRBK3BibU9URll5T2hXL0JraVFkd0F5OWcvekZkTnM1YXVvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFWmpQa2hpVjlEMlZzUU1Kd21NY2hhNEJmL0o0QWpBOXN5VGRVQSszVXRSbnU4aTNkbjNzcQpIVmpaZE01d1NDS0MxR1UyaXZwcCtycFU2SWNmSmJDNFZnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
